name: Docker image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker hub login
        env:
          DOCKER_USER: ${{ secret.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secret.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the docker image
        run: docker build . --file Dockerfile --tag leobozcaitano/react-frontend

      - name: Push the docker image
        run: docker push ${{secret.DOCKER_USER}}/react-frontend
