name: Build Docker image and deploy to k8s

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: DockerHub Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Building the image
        run: docker build . --tag ${{secrets.DOCKER_USER}}/react-frontend

      - name: Push image to dockerhub
        run: docker push ${{secrets.DOCKER_USER}}/react-frontend

      - name: Deploy to cluster
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade react-frontend ./chart-deploy/ --install --wait --atomic --set=app.name=react-frontend --values=./chart-deploy/values.yaml
          kubeconfig: '${{ secrets.KUBE_CONFIG_DATA }}'
