name: Build Docker image and deploy to k8s

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: DockerHub Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Building the image
        run: docker build . --tag ${{secrets.DOCKER_USER}}/react-frontend

      - name: Push image to dockerhub
        run: docker push ${{secrets.DOCKER_USER}}/react-frontend
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Connect to k8s
        run:
